### ISSUE TITLE
OSError: [Errno 3] No such process

### ISSUE THREAD

**Issue by ciquLi** [soufianebny/mininetGoogleMapsAPI#1]
when I input python run.py BTEurope.graphml

Traceback (most recent call last):
  File "run.py", line 41, in <module>
    obj4.initryumininetapi(tabdpid)
  File "scripts/init.py", line 49, in initryumininetapi
    myPopenryu.kill()
  File "/usr/lib/python2.7/subprocess.py", line 1572, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python2.7/subprocess.py", line 1562, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process

IV FINISHED all the steps on ubuntu 16.04
should I setup them with python3??

**Comment by soufianebny** [comment]
python 2.7 is sufficient. Check if ryu-manager is installed in /usr/local/bin/ryu-manager
